/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    MaterialIcon: typeof import('./src/components/MaterialIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskCard: typeof import('./src/components/TaskCard.vue')['default']
    ToggleSwitch: typeof import('./src/components/ToggleSwitch.vue')['default']
    VoiceWave: typeof import('./src/components/VoiceWave.vue')['default']
  }
}
